### ISSUE TITLE
Getting Error....

### ISSUE THREAD

**Issue by sarthakroy2002** [Area69Lab/GSI-Automation#4]
adding: MIUI-AB-10-20201203-ErfanGSI.img (deflated 49%)
spawn sftp ***@frs.sourceforge.net
Password: 
Connected to frs.sourceforge.net.
sftp> cd ***
Couldn't canonicalize: No such file or directory

i added SF_DIR as https://sourceforge.net/projects/sarthak-gsi/files/GSI/....

**Comment by wileylau** [comment]
/home/frs/project/project-name/your-folder/

This should be your SF_DIR. 

Thanks to @nnippon lol, he said this

**Comment by sarthakroy2002** [comment]
will it be directly uploaded to my page in sourceforge?

**Comment by wileylau** [comment]
Yes.

**Comment by sarthakroy2002** [comment]
Last comment : 
it will be 
/home/frs/project/sarthak-gsi/GSI/
for
https://sourceforge.net/projects/sarthak-gsi/files/GSI/

**Comment by wileylau** [comment]
@sarthakroy2002 god damn i forgot sf naming system

**Comment by wileylau** [comment]
@sarthakroy2002 gimme a sec

**Comment by sarthakroy2002** [comment]
ok sir

**Comment by wileylau** [comment]
Yes. Your directory is right @sarthakroy2002
